name: Laravel Tests

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, sqlite3, xdebug
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generate app key
        run: php artisan key:generate

      - name: Create .env file
        run: cp .env.example .env

      - name: Configure database
        run: |
          php artisan config:clear
          php artisan config:cache

      - name: Run tests
        run: php artisan test
        env:
          DB_CONNECTION: sqlite_testing
          DB_DATABASE: ':memory:'
          QUEUE_CONNECTION: 'sync'
